# Pytorch Fundamentals

## import pytorch

In [2]:
import torch

In [3]:
torch.__version__

'2.5.1'

## Tensor

tensor là nền tảng block building trong ML

creating tensors
### scalar
scalar được khởi tạo là một số đơn và trong tensor gọi là tensor không chiều

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

Để lấy số trong scalar, ta dùng item()

In [6]:
scalar.item()

7

### vector

vector là tensor có một chiều, có thể chứa nhiều số

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

### matrix

In [10]:
MATRIX = torch.tensor([[1, 2] , [2, 3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

### tensor

In [13]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### random tensor

Mình có thể dùng hàm rand của torch để tạo một tensor với các số random từ 0 -> 1

In [16]:
random_tensor = torch.rand(size= (5, 5))
random_tensor, random_tensor.dtype

(tensor([[0.7083, 0.7958, 0.6017, 0.5844, 0.0786],
         [0.3719, 0.1918, 0.5391, 0.1348, 0.3616],
         [0.1862, 0.4362, 0.0490, 0.6614, 0.8417],
         [0.5043, 0.8135, 0.4931, 0.4390, 0.2396],
         [0.7877, 0.6582, 0.6114, 0.3690, 0.2581]]),
 torch.float32)

Thử khởi tạo random tensor như là một bức ảnh điii

In [17]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

Mình cũng có thể dùng hàm zeros và ones để tạo các tensor chỉ có toàn số 0 hoặc 1

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
ones = torch.ones(size= (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### tạo một tensor với số trong khoảng định sẵn

Mình sẽ sử dụng hàm torch.arange(start, end, step)

In [20]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Mình cũng có thể sử dụng hàm torch.zeros_like(input) hoặc torch.ones_like(input) để fill tất cả các phần tử trong tensor thành 0 hay 1

In [21]:
full_zeros = torch.zeros_like(zero_to_ten)
full_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
full_ones = torch.ones_like(full_zeros)
full_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## tensor datatypes

trong pytorch có nhiều kiểu dữ liệu khác nhau như torch.cuda, torch.float32, torch.float, torch.half, torch.double, ...

In [23]:
float32tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device= None, requires_grad= False)
float32tensor.shape, float32tensor.dtype, float32tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

có thể thấy một tensor có rất nhiều thông tin

shape: hình dạng của cái tensor

dtype: kiểu dữ liệu của các phần tử ở trong tensor

device: tensor được chứa ở đâu (CPU hay GPU)

In [24]:
some_tensor = torch.rand(3,5)

print(some_tensor)
print(some_tensor.shape, some_tensor.dtype, some_tensor.device)


tensor([[0.8093, 0.8572, 0.8842, 0.9274, 0.1487],
        [0.8997, 0.6048, 0.0974, 0.2512, 0.4510],
        [0.5436, 0.4061, 0.0932, 0.2887, 0.0822]])
torch.Size([3, 5]) torch.float32 cpu


## Tensor operations

Các toán tử của tensor bao gồm: cộng, trừ, nhân, chia, nhân ma trận

In [25]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [26]:
tensor * 10

tensor([10, 20, 30])

lưu ý: có thể thấy sau khi + với * xong thì giá trị tensor vẫn thế, vậy là giá trị tensor không thay đổi khi mình thực hiện phép tính mà không gán nè

In [27]:
tensor

tensor([1, 2, 3])

Giờ mình thử gán rồi thực hiện phép tính nha

In [28]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [29]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Còn đây là phép nhân trên từng phần tử nè, tương tự như việc không gán nên giá trị tensor gốc vẫn không thay đổi nè

In [30]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

nhân 2 tensor với nhau được luôn nè (nhân lần lượt các giá trị phần tử tương ứng)

In [31]:
tensor * tensor

tensor([1, 4, 9])

phép nhân ma trận của pytorch

In [32]:
torch.matmul(tensor, tensor)

tensor(14)

đơn giản hơn nữa thì dùng @

In [33]:
tensor @ tensor

tensor(14)

lưu ý ở đây là việc sử dụng hàm torch.matmul() sẽ nhanh hơn đáng kể nha

### Common error in deep learning

một vài lỗi khá thường gặp đó là việc nhân hai ma trận mà hai ma trận đó không thể nhân nhau do sai về shape ví dụ như: nhân 2 ma trận đều có shape là 2x3

In [34]:

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


Để thực hiện nhân thì ta cần phải chuyển vị ma trận

In [35]:
print(tensor_A.T)
print(tensor_B.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


Thử nhân nè

In [36]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

torch.matmul() còn có thể ghi tắt lại thành torch.mm()

In [37]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])