# Pytorch Fundamentals

## import pytorch

In [1]:
import torch

In [2]:
torch.__version__

'2.5.1'

## Tensor

tensor là nền tảng block building trong ML

creating tensors
### scalar
scalar được khởi tạo là một số đơn và trong tensor gọi là tensor không chiều

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

Để lấy số trong scalar, ta dùng item()

In [9]:
scalar.item()

7

### vector

vector là tensor có một chiều, có thể chứa nhiều số

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

### matrix

In [12]:
MATRIX = torch.tensor([[1, 2] , [2, 3]])
MATRIX

tensor([[1, 2],
        [2, 3]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

### tensor

In [16]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

### random tensor

Mình có thể dùng hàm rand của torch để tạo một tensor với các số random từ 0 -> 1

In [20]:
random_tensor = torch.rand(size= (5, 5))
random_tensor, random_tensor.dtype

(tensor([[0.6429, 0.1990, 0.4718, 0.8641, 0.5576],
         [0.5655, 0.5766, 0.4315, 0.9393, 0.0634],
         [0.4273, 0.7704, 0.4456, 0.1185, 0.4247],
         [0.9679, 0.8731, 0.2325, 0.8786, 0.3246],
         [0.6814, 0.5550, 0.8704, 0.0850, 0.8041]]),
 torch.float32)

Thử khởi tạo random tensor như là một bức ảnh điii

In [21]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

Mình cũng có thể dùng hàm zeros và ones để tạo các tensor chỉ có toàn số 0 hoặc 1

In [23]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [24]:
ones = torch.ones(size= (3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### tạo một tensor với số trong khoảng định sẵn

Mình sẽ sử dụng hàm torch.arange(start, end, step)

In [26]:
zero_to_ten = torch.arange(start = 0, end = 10, step = 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Mình cũng có thể sử dụng hàm torch.zeros_like(input) hoặc torch.ones_like(input) để fill tất cả các phần tử trong tensor thành 0 hay 1

In [27]:
full_zeros = torch.zeros_like(zero_to_ten)
full_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
full_ones = torch.ones_like(full_zeros)
full_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## tensor datatypes

trong pytorch có nhiều kiểu dữ liệu khác nhau như torch.cuda, torch.float32, torch.float, torch.half, torch.double, ...

In [29]:
float32tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device= None, requires_grad= False)
float32tensor.shape, float32tensor.dtype, float32tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

có thể thấy một tensor có rất nhiều thông tin

shape: hình dạng của cái tensor

dtype: kiểu dữ liệu của các phần tử ở trong tensor

device: tensor được chứa ở đâu (CPU hay GPU)

In [30]:
some_tensor = torch.rand(3,5)

print(some_tensor)
print(some_tensor.shape, some_tensor.dtype, some_tensor.device)


tensor([[0.1367, 0.4622, 0.1816, 0.2539, 0.1813],
        [0.0105, 0.4051, 0.3134, 0.2074, 0.4514],
        [0.5902, 0.7920, 0.8596, 0.7383, 0.9883]])
torch.Size([3, 5]) torch.float32 cpu
